version: "3.8"

services:
  runner:
    build:
      context: .
    volumes:
      - .:/scripts
    working_dir: /scripts
    tty: true
    stdin_open: true
    privileged: true
    command: /scripts/script.sh