FROM ubuntu:22.04

# Actualizar el ubuntu
RUN apt-get update && apt-get install -y \
    wget curl gnupg lsb-release build-essential \
    software-properties-common

# Instalar Python 3.13.3 (El que use para el proyecto)
RUN apt-get install -y zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev \
    libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev

RUN wget https://www.python.org/ftp/python/3.13.3/Python-3.13.3.tgz && \
    tar -xf Python-3.13.3.tgz && \
    cd Python-3.13.3 && \
    ./configure --enable-optimizations && \
    make -j$(nproc) && make install && \
    cd .. && rm -rf Python-3.13.3*

# Instalar pip y venv
RUN python3.13 -m ensurepip && python3.13 -m pip install --upgrade pip

# Instalar MySQL 8.0 
RUN apt-get install -y mysql-server

# Instalar Redis 7.2 
RUN add-apt-repository ppa:redislabs/redis -y && \
    apt-get update && \
    apt-get install -y redis

# Crear carpeta para los scripts
WORKDIR /app


COPY scrapping.py almacenamiento.py cache.py trafico.py entrypoint.sh ./

# Instalar dependencias Python (agrega aquí tus requirements si tienes)
RUN python3.13 -m pip install -r requirements.txt

# Dar permisos al entrypoint
RUN chmod +x entrypoint.sh

# Exponer puertos si necesario
EXPOSE 3306 6379

# Ejecutar los scripts en orden
CMD ["./entrypoint.sh"]